name: Deploy versioned & latest

on:
  release:
    types: [published]

jobs:
  deploy-release:
    name: Deploy versioned images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image with latest tag
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }} .
      - name: Push image to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
